"""followers

Revision ID: 335ee11ae124
Revises: 2dc60929a6ca
Create Date: 2019-12-13 13:02:14.787500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335ee11ae124'
down_revision = '2dc60929a6ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
